### ISSUE TITLE
Suggestions about restorer.

### ISSUE THREAD

**Issue by iusearch** [ZombieStriker/ServerRestorer#1]
Saw from spigotmc and immediately search on github, found this. Nice job on this. And do you have any idea about restorer? Just a short thought, a warper of origional server jar file may help. Just replace origional jar with a functional jar generated by the plugin and invoke origional jar later. The server will first run your restorer code then jump into minecraft. Maybe you have better ideas. Put the link on the spigotmc page will help a lot.

**Comment by ZombieStriker** [comment]
Must have forgotten to add this link to the spigot page. The link should now be there.

As for the request, it turns out it is actually easier than I thought. For most regular servers, you can now safely restore the server using /sr restore <backup>. However, if you are using a server hosting service, they may not allow the restoration, as many services do not allow plugins to edit files. If you are using another hosting service, you may still need to restore the server manually.
